import Head from 'next/head';
import Banner from '../components/Banner.jsx';
import Footer from '../components/Footer.jsx';
import Header from '../components/Header.jsx';
import LargeCard from '../components/LargeCard.jsx';
import MediumCard from '../components/MediumCard.jsx';
import SmallCard from '../components/SmallCard.jsx';

export default function Home({ exploreData, cardData }) {
  console.log(cardData);
  return (
    <div>
      <Head>
        <title>Airbnb Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map(({ img, location, distance }, idx) => (
              <SmallCard
                key={idx}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className='text-3xl text-semibold py-8'>Live Anywhere</h2>
          <div className='flex space-x-3 overflow-auto scrollbar-hide '>
            {cardData?.map(({ img, title }) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>
        </section>

        <section>
          <LargeCard
            img='https://links.papareact.com/4cj'
            title='The Greatest Outdoors'
            desc={'Wishlist curated by Airbnb'}
            buttonText='Get Inspired'
          />
        </section>

        <section className='bg-red-400 w-full'>
          <Footer />
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch('https://www.jsonkeeper.com/b/4G1G');
  const exploreData = await res.json();

  const response = await fetch('https://www.jsonkeeper.com/b/VHHT');
  const cardData = await response.json();

  return {
    props: {
      exploreData,
      cardData,
    },
  };
}
